<!DOCTYPE html>
<html>
<head>
    <title>
        <?= $this->hold('resource.header.title', 'Panda Swift') ?>
    </title>

    <style type="text/css">
        body {
            background: rgba(0, 0, 0, 0.8);
            color: #fff;
            width: 35em;
            text-align:right;
            margin: 0 auto;
            padding: 60px 0;
            font-family: 'Myriad Set Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-weight: 100;
        }

        h2 {
          font-weight: 100;
        }
    </style>
</head>
<body>
    <?= $this->inner() ?>
</body>
</html>